### PR TITLE
fix(gas): Remove node key instead of origin id in function consume

### LINKED ISSUE #977: Refactor the algo of getting the gas spent in `get_gas_spent`
### File Location(s)

https://github.com/gear-tech/gear/blob/9bd56a0aa17931985c80ec3fa2377518eacc25bb/pallets/gear/src/lib.rs#L576

### Proposal

We can just get the max gas spent via `JournalNote::GasBurned { amount, .. }`

in case of fixing the node key issue in https://github.com/gear-tech/gear/pull/975, we can not get `remaining_gas` via `T::GasHandler::get_limit(message_id)` after the message has been consumed ( in some cases it would be `None` )

### PR DESCRIPTION
**Pull request by clearloop**
Resolves #977

## Summary

`fn consume` removes `id` insteand of `key` by accident

## Changes

- [x] fix(gas): Remove node key instead of origin id in function consume

## References

- #971
- #977
- #981

### CODE REVIEW

**Comment by clearloop** [comment]
hmmm, looks like this issue related to another new error https://github.com/gear-tech/gear/runs/6611638164?check_suite_focus=true#step:16:598

**Comment by breathx** [comment]
Great find!

Now need to find out the reason of tests failing

**Comment by breathx** [comment]
Great find!

Now need to find out the reason of tests failing

**Comment by clearloop** [comment]
The CI broken because of https://github.com/gear-tech/gear/pull/976#issuecomment-1139916801

**Comment by clearloop** [comment]
#984

**Pull request closed without merging**
