### PR TITLE
fix(wasm-gen): copy data from `HashWithValue` before writing to `err`

### PR DESCRIPTION
**Pull request by StackOverflowExcept1on**
We currently have a problem passing the same pointers as mutable and immutable.

### CODE REVIEW

**Review by breathx — APPROVED** [review]

**Review by techraed — CHANGES_REQUESTED** [review]
Seems odd.
I found the origin of the problem in `build_call_with_destination`, which also affects other cases.

**Comment by breathx** [comment]
> Seems odd. I found the origin of the problem in `build_call_with_destination`, which also affects other cases.

So what to do with the PR?

**Comment by techraed** [comment]
It can still be beneficial if there are syscalls invocations where each param has the same value. We faced the problem during tests when wasm from `[0; N]` buffer forming `Unstructured` was created.
However, that's a rare situation and tests can be re-written with some random seeded data input.

What do you think? @StackOverflowExcept1on

**Comment by StackOverflowExcept1on** [comment]
@techraed I think we can merge this because at least 3 people came across this problem in tests. Rewriting using a seed is not always obvious when copying code from existing tests.

**Comment by techraed** [comment]
Alright, for the sake of tests simplicity let's do that.

**Review by techraed — APPROVED** [review]

**Pull request merged**
