### PR TITLE
chore(workspace): consistent toml style for workspace usages

### PR DESCRIPTION
**Pull request by clearloop**
Resolves # .

```toml
xx.workspace -> xx = { workspace = true }
```

new disscussions about the toml style stuff https://github.com/gear-tech/gear/pull/2643#discussion_r1190871879

the previous one https://github.com/gear-tech/gear/pull/2427#discussion_r1151730537

plz share your options here if you like the short style @gear-tech/dev 

### refs

- https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace

### CODE REVIEW

**Review by DennisInSky — APPROVED** [review]
I am voting for more unified approach

**Comment by shamilsan** [comment]
In such cases, I prefer to examine examples in some core projects. 

Examples:

- https://github.com/rust-lang/rust/blob/master/src/tools/rust-analyzer/crates/cfg/Cargo.toml
- https://github.com/rust-lang/cargo/blob/master/Cargo.toml#L113

So I'd leave the old approach.

**Comment by shamilsan** [comment]
> you change your mind so fast 😅

No, my recommendation was `dep.workspace = true` based on the Rust book. Now it is also based on the Rust core projects.

**Comment by shamilsan** [comment]
> oh, I misunderstood you, thought the consistent you said is between inheriting from workspace and others, now got you mean all `x.worskpace` or `x = { workspace = true }`

Sorry for the confusing, I've edited my comment there.

**Comment by shamilsan** [comment]
Closing as not needed for now.

**Pull request closed without merging**
