### PR TITLE
Load dynamic memory pages for consequent `init` calls

### LINKED ISSUE #599: Dynamic memory pages aren't loaded for consequent `init` calls
### Problem

This is a regression after #515 - `init` may be called several times and use dynamic memory. These pages should be stored and loaded accordingly. Dynamic memory pages don't get loaded at the moment what causes incorrect execution of programs.

### Steps

test-init-wait is edited a bit to reproduce the issue

### Possible Solution

_No response_

### Notes

_No response_

### Relevant Log Output

<details><summary>Click to expand/collapse</summary>
<p>

```
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gwasm] DEBUG: ALLOC ASSERT: 2205
[gear_core_processor::executor] Trap during execution: wasm trap: call stack exhausted
wasm backtrace:
    0: 0xffffffff - <unknown>!memmove
    1: 0x111f0 - <unknown>!<&T as core::fmt::Debug>::fmt::h25049001ff21be92
    2: 0x49a9 - core::char::methods::<impl char>::escape_debug_ext::hf89c1d27ce2b3ff8
                    at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/char/methods.rs:418:26
              - <str as core::fmt::Debug>::fmt::h26161620e0b2e68d
                    at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/fmt/mod.rs:2134:23
    3: 0x1113c - <unknown>!core::ptr::drop_in_place<core::fmt::Error>::hc870b84962f55d64
    4: 0x2d23 - <unknown>!dlmalloc::dlmalloc::Dlmalloc::malloc_internal::hb3faa5db8774af2e
    5: 0x288a - <unknown>!dlmalloc::dlverbose::dlassert_fn::hf972336c27fb65d4
    6: 0x4896 - <core::fmt::Formatter as core::fmt::Write>::write_char::h290726f43c42a751
                    at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/fmt/mod.rs:2065:9
              - <str as core::fmt::Debug>::fmt::h26161620e0b2e68d
                    at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/fmt/mod.rs:2131:9
    7: 0x47b7 - core::fmt::Arguments::new_v1::h882cbc2918f52654
                    at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/core/src/fmt/mod.rs:365:9
              - alloc::vec::Vec<T,A>::swap_remove::assert_failed::h012d66344ead221f
                    at /rustc/6db0a0e9a4a2f55b1a85954e114ada0b45c32e45/library/alloc/src/vec/mod.rs:1300:13
    8: 0x4c30 - <str as core::fmt::Debug>::fmt::h26161620e0b2e68d

```

</p>
</details>

### PR DESCRIPTION
**Pull request by gshep**
Resolves #599 

@gear-tech/dev

### CODE REVIEW

**Review by shamilsan — APPROVED** [review]
Could you please explain why gas limit values have been changed?

**Comment by gshep** [comment]
> Could you please explain why gas limit values have been changed?

After dynamic allocations added to the program the required amount of gas increased. So I adjusted the values.

**Review by breathx — CHANGES_REQUESTED** [review]
Required same changes for charging for initial or loaded pages in `core-processor/executor.rs`

**Review by breathx — APPROVED** [review]
Well done 👍

**Pull request merged**
