### PR TITLE
refactor(runtime-fuzzer): Make gas limit variable in runtime-fuzzer

### LINKED ISSUE #2328: Make gas limit in the fuzzer a randomly generated value
this is about `runtime-fuzzer`

### PR DESCRIPTION
**Pull request by mertwole**
Resolves #2328

### CODE REVIEW

**Comment by SabaunT** [comment]
Actually Im thinking of closing this, becase what can be tested with a low gas value, is actually tested with a max gas value and too expensive program. This case is something common while fuzzer works, as I see from logs. What do you think?

@mertwole @breathx @grishasobol

**Comment by SabaunT** [comment]
due to core-audit/#22 error I think different gas limit values is great for testing.

**Review by breathx — CHANGES_REQUESTED** [review]
Such range will mostly run into small gas amount. I'd make it random, but with much more changes close to default gas limit.
and 100% left border should be > 0

**Comment by SabaunT** [comment]
> 

Makes sense

**Review by breathx — APPROVED** [review]

**Pull request merged**
