### PR TITLE
gas_available syscall

### PR DESCRIPTION
**Pull request by ukint-vs**
- add `msg::gas_available()` in `gstd`

@gear-tech/dev

### CODE REVIEW

**Comment by NikVolf** [comment]
Test were it sends how much gas_available to log would be great

**Comment by ukint-vs** [comment]
> Test were it sends how much gas_available to log would be great

Changed demo-sum to log if gas < 4_000_000_000

**Comment by NikVolf** [comment]
> > Test were it sends how much gas_available to log would be great
> 
> Changed demo-sum to log if gas < 4_000_000_000

and were is the check that it happened exactly for this reason?

**Comment by ukint-vs** [comment]
> > > Test were it sends how much gas_available to log would be great
> > 
> > 
> > Changed demo-sum to log if gas < 4_000_000_000
> 
> and where is the check that it happened exactly for this reason?

done

**Review by NikVolf — APPROVED** [review]

**Pull request merged**
