### PR TITLE
chore: R.I.P. `gear-test`

### PR DESCRIPTION
**Pull request by breathx**
This PR:
* Removes `gear-test` crate
* Removes `gear-runtime-test-cli` crate
* Removes `runtime-spec-tests` node command and `runtime-test` feature
* Removes any `Node.js` entries within the repo
* Removes all associated scripts, bindings and CI jobs (CI and scripts execution time must significantly decrease)
* Moves all `.yamls` in `/spec` dir in order go through them with next PR to figure out some still useful cases to cover with tests and remove legacy demos
* Simplifies and optimises `pallet-gear-debug`

### CODE REVIEW

**Review by ukint-vs — APPROVED** [review]
RIP

**Comment by NikVolf** [comment]
Where are all `/spec` run now?

**Review by NikVolf — CHANGES_REQUESTED** [review]
Before removing, same features should be done in other way

(Test-run examples of all gstd privimitives)

**Comment by SabaunT** [comment]
> 

@breathx I guess we have some tests for gstd primitives on the pallet level. We can separate on the `pallet_gear` pallet specific logic tests and gstd primitives tests with 2 different modules under `cfg(test)`. What do you think?

Can do that after #2534 merging changes to this PR.

**Comment by breathx** [comment]
> > Before removing, same features should be done in other way
> > (Test-run examples of all gstd privimitives)
> 
> @breathx I guess we have some tests for gstd primitives on the pallet level. We can separate on the `pallet_gear` pallet specific logic tests and gstd primitives tests with 2 different modules under `cfg(test)`. What do you think?
> 
> Can do that after #2534 merging changes to this PR.

By @NikVolf request, doing it before merging this one.
I'm going through all yamls, figuring out the useful ones (to don't copy-paste primitives like "program can call syscall") and migrating it into pallet level / gclient examples

**Comment by breathx** [comment]
Already checked out from this branch and making mentioned above changes. My plan is to open PR to this branch (to simplify review process) and merge them into master together within one commit

**Review by grishasobol — APPROVED** [review]

**Comment by shamilsan** [comment]
@breathx
Will we continue gear-test removing in this PR, or will it be done in a separate PR?

**Comment by breathx** [comment]
> @breathx
> Will we continue the gear-test removal in this PR, or will it be done separately?

Doesn't matter. It anyway need rebase

**Comment by breathx** [comment]
Reopened from another branch

**Pull request closed without merging**
