### PR TITLE
refactor(backend-common): Avoid memory accesses on zero size reads

### LINKED ISSUE #2095: Take in account zero size memory accesses in sys-calls.
### Problem to Solve

Currently we can get for example zero size payload in sys-calls. Even in this case this accesses will be handled as common access and host function to get memory will be called and also this access will be pre-processed in lazy-pages.
We need to make separate more fast handling for this accesses in sys-calls.

See also TODO in lazy-pages/src/lib.rs

### PR DESCRIPTION
**Pull request by DennisInSky**
Partially resolves #2095.

- do not access memory on zero size reads

It is not quite clear what needs to be changed/optimised in [lazy-pages](https://github.com/gear-tech/gear/blob/master/lazy-pages/src/host_func.rs#L112) with regards to it. @grishasobol can you please clarify?

@reviewer-or-team

### CODE REVIEW

**Review by shamilsan — APPROVED** [review]
Great 👍

**Review by tltsutltsu — APPROVED** [review]

**Comment by NikVolf** [comment]
@grishasobol ?

**Review by grishasobol — CHANGES_REQUESTED** [review]
Change this comment please https://github.com/gear-tech/gear/blob/11068bc19d39c0e8877ece371be4d07a602260de/lazy-pages/src/host_func.rs#L112-L114

**Comment by DennisInSky** [comment]
> Change this comment please
> 
> https://github.com/gear-tech/gear/blob/11068bc19d39c0e8877ece371be4d07a602260de/lazy-pages/src/host_func.rs#L112-L114

@grishasobol can you please elabortae on how it has to be changed? I asked you about it above - I do not quite understand how it can be optimised or how the comment has to be changed.

**Review by grishasobol — APPROVED** [review]

**Pull request merged**
