### PR TITLE
Merge imports

### PR DESCRIPTION
**Pull request by ark0f**
This is what reviewers sometimes ask for

`rustfmt` now automatically merge imports

### CODE REVIEW

**Review by breathx — APPROVED** [review]
Great!
Could rustfmt.toml also add newlines at the end of the file if programmer's editor isn't configured enough?

**Comment by ark0f** [comment]
> Great! Could rustfmt.toml also add newlines at the end of the file if programmer's editor isn't configured enough?

Unfortunately not

**Comment by SabaunT** [comment]
:+1:

**Review by shamilsan — APPROVED** [review]

**Comment by shamilsan** [comment]
> Great! Could rustfmt.toml also add newlines at the end of the file if programmer's editor isn't configured enough?

It does it by default in *.rs files.

**Pull request merged**
