### PR TITLE
Add CI workflow for release

### PR DESCRIPTION
**Pull request by shamilsan**
- Added vara-runtime artifacts
- Added CI workflow for release

### CODE REVIEW

**Comment by NikVolf** [comment]
Will it create a draft ?

**Comment by shamilsan** [comment]
> Will it create a draft ?

No, it will create a public release. I can change it to make a non-public draft first.

**Comment by NikVolf** [comment]
Yeah, actual release should be manual

**Comment by shamilsan** [comment]
> Yeah, actual release should be manual

Fixed.

**Review by NikVolf — APPROVED** [review]

**Pull request merged**
