### PR TITLE
chore(depbot): not skipping ci

### LINKED ISSUE #3310: Not skipping CI in dependency updates
### Problem to Solve

https://github.com/gear-tech/gear/blob/master/.github/dependabot.yml#L10

### Possible Solution

basically just remove this line, then,  add `A0-pleaseview`

### Notes

_No response_

### PR DESCRIPTION
**Pull request by clearloop**
Resolves #3310

not skipping CI in the PRs of depbot

@gear-tech/dev

### CODE REVIEW

**Review by StackOverflowExcept1on — APPROVED** [review]

**Review by NikVolf — APPROVED** [review]
won't it cripple our ci with many prs ?

**Comment by clearloop** [comment]
> won't it cripple our ci with many prs ?

yeah it is possible )))

**Comment by NikVolf** [comment]
> > won't it cripple our ci with many prs ?
> 
> yeah it is possible )))

i think those updates can be batched

**Comment by shamilsan** [comment]
> i think those updates can be batched

They are batched here: https://github.com/gear-tech/gear/blob/master/.github/workflows/combined-dependabot.yml

**Comment by clearloop** [comment]
what if we `[skip-ci]` for dependabot's PRs and run full actions in the combined PR?

**Pull request merged**
