### PR TITLE
DRAFT: chore: Prebuilt dependencies

### PR DESCRIPTION
**Pull request by gshep**
@reviewer-or-team

`$ cargo  build -p gear-cli --timings`

On AMD Ryzen 7 3700X running Ubuntu 20.04 x86_64:
<details><summary>Without prebuilt packages:</summary>

<h1>Cargo Build Timings</h1>

<table class="my-table summary-table">
  <tr>
    <td>Targets:</td><td>gear-cli 1.2.1 (lib, bin "gear")</td>
  </tr>
  <tr>
    <td>Profile:</td><td>dev</td>
  </tr>
  <tr>
    <td>Fresh units:</td><td>0</td>
  </tr>
  <tr>
    <td>Dirty units:</td><td>1149</td>
  </tr>
  <tr>
    <td>Total units:</td><td>1149</td>
  </tr>
  <tr>
    <td>Max concurrency:</td><td>20 (jobs=16 ncpu=16)</td>
  </tr>
  <tr>
    <td>Build start:</td><td>2024-04-05T08:42:25Z</td>
  </tr>
  <tr>
    <td>Total time:</td><td>283.5s (4m 43.5s)</td>
  </tr>
  <tr>
    <td>rustc:</td><td>rustc 1.77.0-nightly (7ffc697ce 2024-01-24)<br>Host: x86_64-unknown-linux-gnu<br>Target: x86_64-unknown-linux-gnu</td>
  </tr>

</table>

<table class="my-table">
  <thead>
    <tr>
      <th></th>
      <th>Unit</th>
      <th>Total</th>
      <th>Codegen</th>
      <th>Features</th>
    </tr>
  </thead>
  <tbody>

<tr>
  <td>1.</td>
  <td>librocksdb-sys v0.11.0+8.1.1 build script (run)</td>
  <td>134.0s</td>
  <td></td>
  <td>default, jemalloc, snappy, static, tikv-jemalloc-sys</td>
</tr>

<tr>
  <td>2.</td>
  <td>wasm-opt-sys v0.114.2 build script (run)</td>
  <td>92.8s</td>
  <td></td>
  <td>default</td>
</tr>

<tr>
  <td>3.</td>
  <td>vara-runtime v1.2.1 build script (run)</td>
  <td>78.7s</td>
  <td></td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>4.</td>
  <td>zstd-sys v2.0.8+zstd.1.5.5 build script (run)</td>
  <td>57.9s</td>
  <td></td>
  <td>std</td>
</tr>

<tr>
  <td>5.</td>
  <td>tikv-jemalloc-sys v0.5.4+5.3.0-patched build script (run)</td>
  <td>49.3s</td>
  <td></td>
  <td>background_threads_runtime_support, default, unprefixed_malloc_on_supported_platforms</td>
</tr>

<tr>
  <td>6.</td>
  <td>secp256k1-sys v0.6.1 build script (run)</td>
  <td>43.1s</td>
  <td></td>
  <td>alloc, recovery, std</td>
</tr>

<tr>
  <td>7.</td>
  <td>blake3 v1.3.1 build script (run)</td>
  <td>36.1s</td>
  <td></td>
  <td>default, digest, std</td>
</tr>

<tr>
  <td>8.</td>
  <td>gear-cli v1.2.1 bin "gear"</td>
  <td>28.3s</td>
  <td></td>
  <td>default, pallet-gear-staking-rewards, vara-native, vara-runtime</td>
</tr>

<tr>
  <td>9.</td>
  <td>cranelift-codegen v0.95.1</td>
  <td>22.8s</td>
  <td>14.7s (65%)</td>
  <td>default, gimli, std, trace-log, unwind</td>
</tr>

<tr>
  <td>10.</td>
  <td>gear-service v1.2.1</td>
  <td>21.9s</td>
  <td>14.8s (67%)</td>
  <td>pallet-im-online, pallet-staking, sp-authority-discovery, vara-native, vara-runtime</td>
</tr>

<tr>
  <td>11.</td>
  <td>cranelift-codegen v0.82.3</td>
  <td>19.1s</td>
  <td>10.8s (57%)</td>
  <td>arm64, gimli, std, unwind, x86</td>
</tr>

<tr>
  <td>12.</td>
  <td>lz4-sys v1.9.4 build script (run)</td>
  <td>18.5s</td>
  <td></td>
  <td></td>
</tr>

<tr>
  <td>13.</td>
  <td>frame-support v4.0.0-dev</td>
  <td>13.8s</td>
  <td>0.6s (4%)</td>
  <td>default, sp-state-machine, std</td>
</tr>

<tr>
  <td>14.</td>
  <td>frame-support-procedural v4.0.0-dev</td>
  <td>12.7s</td>
  <td></td>
  <td>std</td>
</tr>

<tr>
  <td>15.</td>
  <td>wasmer-compiler-singlepass v2.3.0</td>
  <td>12.6s</td>
  <td>7.4s (58%)</td>
  <td>avx, default, gimli, rayon, std, unwind</td>
</tr>
</tbody>
</table>
</details>

<details><summary>With prebuilt packages:</summary>
<h1>Cargo Build Timings</h1>

<table class="my-table summary-table">
  <tr>
    <td>Targets:</td><td>gear-cli 1.2.1 (lib, bin "gear")</td>
  </tr>
  <tr>
    <td>Profile:</td><td>dev</td>
  </tr>
  <tr>
    <td>Fresh units:</td><td>0</td>
  </tr>
  <tr>
    <td>Dirty units:</td><td>1149</td>
  </tr>
  <tr>
    <td>Total units:</td><td>1149</td>
  </tr>
  <tr>
    <td>Max concurrency:</td><td>16 (jobs=16 ncpu=16)</td>
  </tr>
  <tr>
    <td>Build start:</td><td>2024-04-05T10:56:28Z</td>
  </tr>
  <tr>
    <td>Total time:</td><td>159.3s (2m 39.3s)</td>
  </tr>
  <tr>
    <td>rustc:</td><td>rustc 1.77.0-nightly (7ffc697ce 2024-01-24)<br>Host: x86_64-unknown-linux-gnu<br>Target: x86_64-unknown-linux-gnu</td>
  </tr>

</table>

<table class="my-table">
  <thead>
    <tr>
      <th></th>
      <th>Unit</th>
      <th>Total</th>
      <th>Codegen</th>
      <th>Features</th>
    </tr>
  </thead>
  <tbody>

<tr>
  <td>1.</td>
  <td>vara-runtime v1.2.1 build script (run)</td>
  <td>54.2s</td>
  <td></td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>2.</td>
  <td>cranelift-codegen v0.82.3</td>
  <td>22.8s</td>
  <td>14.5s (63%)</td>
  <td>arm64, gimli, std, unwind, x86</td>
</tr>

<tr>
  <td>3.</td>
  <td>cranelift-codegen v0.95.1</td>
  <td>22.5s</td>
  <td>14.5s (64%)</td>
  <td>default, gimli, std, trace-log, unwind</td>
</tr>

<tr>
  <td>4.</td>
  <td>gear-cli v1.2.1 bin "gear"</td>
  <td>22.0s</td>
  <td></td>
  <td>default, pallet-gear-staking-rewards, vara-native, vara-runtime</td>
</tr>

<tr>
  <td>5.</td>
  <td>gear-service v1.2.1</td>
  <td>21.3s</td>
  <td>14.5s (68%)</td>
  <td>pallet-im-online, pallet-staking, sp-authority-discovery, vara-native, vara-runtime</td>
</tr>

<tr>
  <td>6.</td>
  <td>frame-support v4.0.0-dev</td>
  <td>13.9s</td>
  <td>0.6s (4%)</td>
  <td>default, sp-state-machine, std</td>
</tr>

<tr>
  <td>7.</td>
  <td>wasmer-compiler-singlepass v2.3.0</td>
  <td>13.0s</td>
  <td>7.7s (60%)</td>
  <td>avx, default, gimli, rayon, std, unwind</td>
</tr>

<tr>
  <td>8.</td>
  <td>frame-support-procedural v4.0.0-dev</td>
  <td>13.0s</td>
  <td></td>
  <td>std</td>
</tr>

<tr>
  <td>9.</td>
  <td>ark-ff v0.4.2</td>
  <td>10.9s</td>
  <td>0.1s (1%)</td>
  <td>std</td>
</tr>

<tr>
  <td>10.</td>
  <td>wast v70.0.0</td>
  <td>10.6s</td>
  <td>5.9s (56%)</td>
  <td>default, wasm-module</td>
</tr>

<tr>
  <td>11.</td>
  <td>vara-runtime v1.2.1</td>
  <td>10.6s</td>
  <td>5.4s (51%)</td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>12.</td>
  <td>sc-network v0.10.0-dev</td>
  <td>9.5s</td>
  <td>5.9s (62%)</td>
  <td>default</td>
</tr>

<tr>
  <td>13.</td>
  <td>wasmtime v8.0.1</td>
  <td>8.6s</td>
  <td>5.7s (67%)</td>
  <td>cache, cranelift, jitdump, parallel-compilation, pooling-allocator</td>
</tr>

<tr>
  <td>14.</td>
  <td>sp-api-proc-macro v4.0.0-dev</td>
  <td>7.9s</td>
  <td></td>
  <td>default, frame-metadata, std</td>
</tr>

<tr>
  <td>15.</td>
  <td>regalloc v0.0.34</td>
  <td>7.7s</td>
  <td>5.7s (74%)</td>
  <td>default</td>
</tr>
</tbody>
</table>
</details>

<table class="my-table summary-table">
<thead>
    <th></th>
    <th>Usual packages</th>
    <th>Prebuilt packages</th>
</thead>
<tbody>
  <tr>
    <td>Total time:</td><td>283.5s (4m 43.5s)</td><td>159.3s (2m 39.3s)</td>
  </tr>
</tbody>
</table>
<br/>
<br/>
On Apple Silicon M1:
<details><summary>Without prebuilt packages:</summary>
<h1>Cargo Build Timings</h1>

<table class="my-table summary-table">
  <tr>
    <td>Targets:</td><td>gear-cli 1.2.1 (lib, bin "gear")</td>
  </tr>
  <tr>
    <td>Profile:</td><td>dev</td>
  </tr>
  <tr>
    <td>Fresh units:</td><td>0</td>
  </tr>
  <tr>
    <td>Dirty units:</td><td>1141</td>
  </tr>
  <tr>
    <td>Total units:</td><td>1141</td>
  </tr>
  <tr>
    <td>Max concurrency:</td><td>12 (jobs=8 ncpu=8)</td>
  </tr>
  <tr>
    <td>Build start:</td><td>2024-04-05T13:33:37Z</td>
  </tr>
  <tr>
    <td>Total time:</td><td>329.8s (5m 29.8s)</td>
  </tr>
  <tr>
    <td>rustc:</td><td>rustc 1.77.0-nightly (7ffc697ce 2024-01-24)<br>Host: aarch64-apple-darwin<br>Target: aarch64-apple-darwin</td>
  </tr>

</table>

<table class="my-table">
  <thead>
    <tr>
      <th></th>
      <th>Unit</th>
      <th>Total</th>
      <th>Codegen</th>
      <th>Features</th>
    </tr>
  </thead>
  <tbody>

<tr>
  <td>1.</td>
  <td>librocksdb-sys v0.11.0+8.1.1 build script (run)</td>
  <td>190.3s</td>
  <td></td>
  <td>default, jemalloc, snappy, static, tikv-jemalloc-sys</td>
</tr>

<tr>
  <td>2.</td>
  <td>wasm-opt-sys v0.114.2 build script (run)</td>
  <td>126.3s</td>
  <td></td>
  <td>default</td>
</tr>

<tr>
  <td>3.</td>
  <td>vara-runtime v1.2.1 build script (run)</td>
  <td>94.1s</td>
  <td></td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>4.</td>
  <td>zstd-sys v2.0.8+zstd.1.5.5 build script (run)</td>
  <td>86.9s</td>
  <td></td>
  <td>std</td>
</tr>

<tr>
  <td>5.</td>
  <td>secp256k1-sys v0.6.1 build script (run)</td>
  <td>57.5s</td>
  <td></td>
  <td>alloc, recovery, std</td>
</tr>

<tr>
  <td>6.</td>
  <td>tikv-jemalloc-sys v0.5.4+5.3.0-patched build script (run)</td>
  <td>31.7s</td>
  <td></td>
  <td>background_threads_runtime_support, default, unprefixed_malloc_on_supported_platforms</td>
</tr>

<tr>
  <td>7.</td>
  <td>gear-service v1.2.1</td>
  <td>24.3s</td>
  <td>16.5s (68%)</td>
  <td>pallet-im-online, pallet-staking, sp-authority-discovery, vara-native, vara-runtime</td>
</tr>

<tr>
  <td>8.</td>
  <td>cranelift-codegen v0.82.3</td>
  <td>16.9s</td>
  <td>10.7s (63%)</td>
  <td>arm64, gimli, std, unwind, x86</td>
</tr>

<tr>
  <td>9.</td>
  <td>cranelift-codegen v0.95.1</td>
  <td>16.3s</td>
  <td>11.2s (69%)</td>
  <td>default, gimli, std, trace-log, unwind</td>
</tr>

<tr>
  <td>10.</td>
  <td>lz4-sys v1.9.4 build script (run)</td>
  <td>15.1s</td>
  <td></td>
  <td></td>
</tr>

<tr>
  <td>11.</td>
  <td>frame-support v4.0.0-dev</td>
  <td>13.0s</td>
  <td>0.4s (3%)</td>
  <td>default, sp-state-machine, std</td>
</tr>

<tr>
  <td>12.</td>
  <td>vara-runtime v1.2.1</td>
  <td>12.0s</td>
  <td>6.8s (56%)</td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>13.</td>
  <td>wasmer-compiler-singlepass v2.3.0</td>
  <td>10.0s</td>
  <td>5.8s (58%)</td>
  <td>avx, default, gimli, rayon, std, unwind</td>
</tr>

<tr>
  <td>14.</td>
  <td>wast v70.0.0</td>
  <td>9.2s</td>
  <td>5.3s (58%)</td>
  <td>default, wasm-module</td>
</tr>

<tr>
  <td>15.</td>
  <td>frame-support-procedural v4.0.0-dev</td>
  <td>8.2s</td>
  <td></td>
  <td>std</td>
</tr>
</tbody>
</table>
</details>

<details><summary>With prebuilt packages:</summary>
<h1>Cargo Build Timings</h1>
See <a href="[https://doc.rust-lang.org/nightly/cargo/reference/timings.html](view-source:https://doc.rust-lang.org/nightly/cargo/reference/timings.html)">Documentation</a>

<table class="my-table summary-table">
  <tr>
    <td>Targets:</td><td>gear-cli 1.2.1 (lib, bin "gear")</td>
  </tr>
  <tr>
    <td>Profile:</td><td>dev</td>
  </tr>
  <tr>
    <td>Fresh units:</td><td>0</td>
  </tr>
  <tr>
    <td>Dirty units:</td><td>1141</td>
  </tr>
  <tr>
    <td>Total units:</td><td>1141</td>
  </tr>
  <tr>
    <td>Max concurrency:</td><td>8 (jobs=8 ncpu=8)</td>
  </tr>
  <tr>
    <td>Build start:</td><td>2024-04-05T13:41:05Z</td>
  </tr>
  <tr>
    <td>Total time:</td><td>247.9s (4m 7.9s)</td>
  </tr>
  <tr>
    <td>rustc:</td><td>rustc 1.77.0-nightly (7ffc697ce 2024-01-24)<br>Host: aarch64-apple-darwin<br>Target: aarch64-apple-darwin</td>
  </tr>

</table>

<table class="my-table">
  <thead>
    <tr>
      <th></th>
      <th>Unit</th>
      <th>Total</th>
      <th>Codegen</th>
      <th>Features</th>
    </tr>
  </thead>
  <tbody>

<tr>
  <td>1.</td>
  <td>vara-runtime v1.2.1 build script (run)</td>
  <td>73.2s</td>
  <td></td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>2.</td>
  <td>gear-service v1.2.1</td>
  <td>24.1s</td>
  <td>16.4s (68%)</td>
  <td>pallet-im-online, pallet-staking, sp-authority-discovery, vara-native, vara-runtime</td>
</tr>

<tr>
  <td>3.</td>
  <td>cranelift-codegen v0.82.3</td>
  <td>20.3s</td>
  <td>13.5s (67%)</td>
  <td>arm64, gimli, std, unwind, x86</td>
</tr>

<tr>
  <td>4.</td>
  <td>cranelift-codegen v0.95.1</td>
  <td>17.9s</td>
  <td>12.5s (70%)</td>
  <td>default, gimli, std, trace-log, unwind</td>
</tr>

<tr>
  <td>5.</td>
  <td>frame-support v4.0.0-dev</td>
  <td>13.2s</td>
  <td>0.5s (3%)</td>
  <td>default, sp-state-machine, std</td>
</tr>

<tr>
  <td>6.</td>
  <td>wasmer-compiler-singlepass v2.3.0</td>
  <td>11.8s</td>
  <td>7.1s (61%)</td>
  <td>avx, default, gimli, rayon, std, unwind</td>
</tr>

<tr>
  <td>7.</td>
  <td>sc-network v0.10.0-dev</td>
  <td>11.6s</td>
  <td>8.5s (73%)</td>
  <td>default</td>
</tr>

<tr>
  <td>8.</td>
  <td>vara-runtime v1.2.1</td>
  <td>11.5s</td>
  <td>6.7s (58%)</td>
  <td>dev, pallet-gear-debug, pallet-sudo, std, substrate-wasm-builder</td>
</tr>

<tr>
  <td>9.</td>
  <td>wast v70.0.0</td>
  <td>10.1s</td>
  <td>5.9s (58%)</td>
  <td>default, wasm-module</td>
</tr>

<tr>
  <td>10.</td>
  <td>frame-support-procedural v4.0.0-dev</td>
  <td>9.0s</td>
  <td></td>
  <td>std</td>
</tr>

<tr>
  <td>11.</td>
  <td>wasmtime v8.0.1</td>
  <td>8.0s</td>
  <td>5.5s (69%)</td>
  <td>cache, cranelift, jitdump, parallel-compilation, pooling-allocator</td>
</tr>

<tr>
  <td>12.</td>
  <td>regalloc v0.0.34</td>
  <td>7.5s</td>
  <td>5.7s (77%)</td>
  <td>default</td>
</tr>

<tr>
  <td>13.</td>
  <td>wasmparser-nostd v0.100.1</td>
  <td>7.0s</td>
  <td>4.3s (61%)</td>
  <td>std</td>
</tr>

<tr>
  <td>14.</td>
  <td>nalgebra v0.32.3</td>
  <td>6.8s</td>
  <td>0.1s (1%)</td>
  <td>default, macros, matrixmultiply, nalgebra-macros, std</td>
</tr>

<tr>
  <td>15.</td>
  <td>ark-ff v0.4.2</td>
  <td>6.7s</td>
  <td>0.1s (1%)</td>
  <td>std</td>
</tr>
</tbody>
</table>
</details>

<table class="my-table summary-table">
<thead>
    <th></th>
    <th>Usual packages</th>
    <th>Prebuilt packages</th>
</thead>
<tbody>
  <tr>
    <td>Total time:</td><td>329.8s (5m 29.8s)</td><td>247.9s (4m 7.9s)</td>
  </tr>
</tbody>
</table>

### CODE REVIEW

**Comment by gshep** [comment]
check wasm-opt for details - https://github.com/gear-tech/wasm-opt-rs/commit/182634ddc380728b3fcd7c8a90a5fdfb25330188

**Comment by StackOverflowExcept1on** [comment]
Another idea on how to do this without supporting forks:
1. patch `cc-rs`: https://github.com/gear-tech/cc-rs/commit/7a299d973c1b721a7e33acc456b6d9d10ba6e142
2. set `JEMALLOC_OVERRIDE=/path/to/libjemalloc_pic.a`: https://github.com/tikv/jemallocator/blob/4f35ea85e25b4f9e304b8d9ce163f5f648a12311/jemalloc-sys/build.rs#L112
3. write simple bash scripts to manage env vars: https://github.com/gear-tech/gear/compare/master...av/dependency-overloading

Results:
```
$ git checkout av/dependency-overloading

$ mkdir -p prebuilt-libraries
$ ./scripts/prebuilt-libraries-dump.sh prebuilt-libraries

Finished release [optimized] target(s) in 11m 32s

$ source ./scripts/prebuilt-libraries.sh prebuilt-libraries
$ ./scripts/gear.sh build node --release --locked

Finished release [optimized] target(s) in 7m 08s (speed up: 4m 24s)
```

**Comment by ark0f** [comment]
This idea requires to support a lot of forks. I think few minutes of initial build doesn't worth support of all these forks. Also, custom crate registry looks like potential vulnerability.

---

The first suggestion.

We can set env vars for some deps to use prebuilt binaries from system:
- RocksDB. `ROCKSDB_INCLUDE_DIR`, `ROCKSDB_LIB_DIR`
- snappy. `SNAPPY_INCLUDE_DIR`, `SNAPPY_LIB_DIR`
- zstd. `ZSTD_SYS_USE_PKG_CONFIG`
- tikv-jemalloc. `JEMALLOC_OVERRIDE`

For other libraries we can just send patches to original repos to support usage of system libraries. But this suggestion doesn't guarantee right feature set or version for each library.

---

The second suggestion.

Also, why do we run `cargo clean`? Because build artifacts take some disk space. So there is official but __unstable__ solution:
https://blog.rust-lang.org/2023/12/11/cargo-cache-cleaning.html

**Comment by breathx** [comment]
> This idea requires to support a lot of forks. I think few minutes of initial build doesn't worth support of all these forks. Also, custom crate registry looks like potential vulnerability.
> 
> We can set env vars for some deps to use prebuilt binaries from system:
> 
> * RocksDB. `ROCKSDB_INCLUDE_DIR`, `ROCKSDB_LIB_DIR`
> * snappy. `SNAPPY_INCLUDE_DIR`, `SNAPPY_LIB_DIR`
> * zstd. `ZSTD_SYS_USE_PKG_CONFIG`
> * tikv-jemalloc. `JEMALLOC_OVERRIDE`
> 
> For other libraries we can just send patches to original repos to support usage of system libraries. But this suggestion doesn't guarantee right feature set or version for each library.

To sum up, I agree with @ark0f and keep pushing my point from our sync: there is no incentive to waste that much time and decreasing stability, increasing complexity of the project, just to compile something 1 min faster

**Review by breathx — CHANGES_REQUESTED** [review]
Explained above

**Pull request closed without merging**
