### PR TITLE
Merge branch 'master' into vara-stage-1

### PR DESCRIPTION
**Pull request by ukint-vs**
Merge master branch into vara-stage-1

@gear-tech/dev

### CODE REVIEW

**Review by ekovalev — APPROVED** [review]

**Comment by NikVolf** [comment]
Can you squash all commits besides merge one in one commit and merge without squashing?

**Review by NikVolf — CHANGES_REQUESTED** [review]
All commits after merge should be squashed in advance

**Review by breathx — CHANGES_REQUESTED** [review]
Discussed personally methodic of merging with commit picking

**Review by breathx — APPROVED** [review]

**Review by NikVolf — APPROVED** [review]
merge without squashing

**Pull request merged**
