### PR TITLE
Create docker-compose.yaml.j3

### PR DESCRIPTION
**Pull request by gmustdie**

### CODE REVIEW

**Comment by breathx** [comment]
Will it purge chain each time we merge something into master?

**Comment by breathx** [comment]
I would also rename PR's header on what it actually does

**Comment by NikVolf** [comment]
So a description of what it does would be nice

**Comment by gmustdie** [comment]
No, it will not. Pipe will start only when manually started.

**Comment by shamilsan** [comment]
What is the state of this PR? It seems to be similar to https://github.com/gear-tech/gear/pull/436

@gmustdie

**Comment by shamilsan** [comment]
Closing it as a stale one. Reopen if needed.

**Pull request closed without merging**
