### PR TITLE
CI: Fix nightly toolchain version to 2022-03-22

### PR DESCRIPTION
**Pull request by shamilsan**
Try to fix CI.

### CODE REVIEW

**Review by grishasobol — APPROVED** [review]

**Comment by breathx** [comment]
So can't we avoid manual specifying of toolchain in scripts?

**Review by breathx — CHANGES_REQUESTED** [review]
Need to somehow throw available toolchain. My version is different so all build scripts gonna fail locally. Need to think in envvars way

**Comment by shamilsan** [comment]
> Need to somehow throw available toolchain. My version is different so all build scripts gonna fail locally. Need to think in envvars way

`rust-toolchain.toml` forces to install `nightly-2022-03-22` locally. So you'll have several nightly versions. Is it ok?

**Comment by ark0f** [comment]
Maybe it will be easier to [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) ring using https://github.com/briansmith/ring/pull/1470?

**Comment by shamilsan** [comment]
> Maybe it will be easier to [patch](https://doc.rust-lang.org/cargo/reference/overriding-dependencies.html) ring using [briansmith/ring#1470](https://github.com/briansmith/ring/pull/1470)?

`ring` is the indirect dependency as I see. May we patch some kind of crates?

**Comment by ark0f** [comment]
The feature allows to patch indirect dependencies, too

**Comment by shamilsan** [comment]
The solution in #795 looks better. 

@ark0f thanks for advice 👍

**Pull request closed without merging**
