### PR TITLE
refactor(core): Add `gr_user_break` syscall to replace all non returning syscalls.

### LINKED ISSUE #3216: Proposal: introduce gr_break
### Problem to Solve

Currently we have 8 non-return syscalls:
```
gr_panic(payload: *const BufferStart, len: Length)
gr_oom_panic()
gr_exit(inheritor_id: *const Hash)
gr_leave()
gr_wait_for(duration: BlockNumber)
gr_wait_up_to(duration: BlockNumber)
gr_wait()
gr_out_of_gas()
```

Aslo we need one more sys-call `gr_stack_overflow` for stack limit exceeded (currently simple unreachable is using). Unfortunately instruction `unreachable` has no literal argument, so we cannot use it to identify the reason of unreachable execution. 

So, the problem is that for each one new special exit from execution reason we need to make separate sys-call, which cause problems in support, code size, code complexity and etc. 

### Possible Solution

Make two sys-calls instead:
```
gr_user_break(data: u64) -> !;
gr_system_break(data: u64) -> !;
```

`gr_user_break` is instead of all user available sys-calls. `data` contains next information:
1) `data.to_le_bytes[0]` - contains code of sys-call functionality. Should it act like gr_panic, gr_leave, gr_exit and etc.
2) `data.to_le_bytes[1]` - contains custom user information code. For some sys-calls it can be useful. For example: instead of panic with some panic string program can panic with some code and send this code in system reply.
3) in bytes `data.to_le_bytes[2..8]` special sys-call data is encoded (not scale codec). For example for `gr_wait_for` is `BlockNumber`. For `gr_panic` `data.to_le_bytes[2..6]` is  `*const BufferStart` and `data.to_le_bytes[6..8]` is `Length` (65536 bytes for panic payload should be enough)

`gr_system_break` is instead of `gr_out_of_gas` and `gr_stack_overflow`. Argument `data` just identifies whether it's `out_of_gas` or  `stack_overflow` occur.

### Notes

The signatures of this sys-calls can be expanded for more flexibility. For example:
```
gr_user_break(code: u64, data: u64) -> !;
gr_system_break(code: u64, data: u64) -> !;
```

gr_system_break will be restricted at instrumentation in original user code

### PR DESCRIPTION
**Pull request by mqxf**
Resolves #3216 

@reviewer-or-team

### CODE REVIEW

**Comment by breathx** [comment]
First of all, the issue is already solved. No idea why GitHub shows only reference.
Secondly, you can't just remove support for some already existing on-chain calls

**Comment by mqxf** [comment]
The issue wasn't solved, since he mentioned two syscalls, gr_system_break, which was solved, and gr_user_break, which wasn't. I asked around before making this issue and I am not removing any support, we are just moving any syscalls that dont return into one syscall, since they don't take many arguments.

**Comment by breathx** [comment]
> The issue wasn't solved, since he mentioned two syscalls, gr_system_break, which was solved, and gr_user_break, which wasn't. 

https://github.com/gear-tech/gear/pull/3512#pullrequestreview-1756139921 It was discussed that other changes are redundant and incorrect. 

> I asked around before making this issue and I am not removing any support, we are just moving any syscalls that dont return into one syscall, since they don't take many arguments.

As I can see, you've removed support for previously existing programs, because old signatures of syscalls no longer exist.

**Comment by mqxf** [comment]
I see. A bit of a stretch, but if this is useful enough, could some sort of "migrations" be used, where when a program is loaded, I could write some code which would check if it imports syscalls and replace the uses of those syscalls with the new break syscall? Probably not, but just an idea.

**Pull request closed without merging**
