### PR TITLE
Fix build with rustc 1.60.0-nightly (5e57faa78 2022-01-19)

### PR DESCRIPTION
**Pull request by gshep**
@gear-tech/dev

### CODE REVIEW

**Review by shamilsan — APPROVED** [review]

**Comment by breathx** [comment]
Need to remove these optional deps so

**Review by breathx — APPROVED** [review]

**Comment by shamilsan** [comment]
> Need to remove these optional deps so

As I see we need to move them to `[dev-dependencies]`.

**Comment by breathx** [comment]
> > Need to remove these optional deps so
> 
> As I see we need to move them to `[dev-dependencies]`.

Why? Don't see their usage in `tests/btree`, e.g.

I think they are unused stuff, that we forget to remove after migration on `core-processor`.

**Comment by shamilsan** [comment]
> Why? Don't see their usage in tests.
> 
> I think they are unused stuff, that we forget to remove after migration on `core-processor`.

At least `common` is used: 

https://github.com/gear-tech/gear/blob/master/tests/btree/src/lib.rs#L103

**Comment by breathx** [comment]
> > Why? Don't see their usage in tests.
> > I think they are unused stuff, that we forget to remove after migration on `core-processor`.
> 
> At least `common` is used:
> 
> https://github.com/gear-tech/gear/blob/master/tests/btree/src/lib.rs#L103

Ah, yeah, found it.

Need to recheck it. Somewhere it's unused, as I see. Somewhere we **should** replace `gear_core::MessageId` with `gstd::MessageId` and remove unused dep, because it's more correct in gear-programs.

**Review by shamilsan — CHANGES_REQUESTED** [review]
> Ah, yeah, found it.
> 
> Need to recheck it. Somewhere it's unused, as I see. Somewhere we **should** replace `gear_core::MessageId` with `gstd::MessageId` and remove unused dep, because it's more correct in gear-programs
> 
> https://github.com/gear-tech/gear/blob/d5219307fae465d790c1814477536d134c86aaa5/tests/wait_wake/src/lib.rs#L63
> .

Agree. @gshep please review all dependencies in standalone tests and leave only these are really needed.

**Review by shamilsan — APPROVED** [review]
I don't mind if @breathx has no concerns about `gear_core::MessageId`.

**Review by breathx — APPROVED** [review]

**Pull request merged**
